# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='shoe', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='woman', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='shoe1.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
